name: CI/CD Pipeline

on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2
      - name: Instalar dependencias
        working-directory: ./backend
        run: npm install
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2
      - name: Instalar dependencias
        working-directory: ./frontend
        run: npm install
      - name: Ejecutar pruebas unitarias
        working-directory: ./frontend
        run: npm test
  docker:
    name: Docker Compose Build & Run
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Levantar servicios con Docker Compose
        run: docker compose up --build -d

      - name: Verificar contenedores en ejecución
        run: docker ps

      - name: Apagar y limpiar contenedores
        if: always()
        run: docker compose down